---
title: "Predicting NBA Minutes played"
Author: "Robert Miller"
output: html_document
date: "2022-12-09"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
devtools::install_github("abresler/nbastatR")
library(nbastatR)
library(tidymodels)
library(corrplot)
library(tidyverse)
library(dplyr)
library(ggplot2)
library(pracma)
```
Data cleaning
```{r}
NBA_Player_box_scores <- read.csv("2012-18_playerBoxScore.csv")

NBA_Player_box_scores$teamRslt <- as.factor(NBA_Player_box_scores$teamRslt)



box<- box_scores(0022100001:0022100002, box_score_types = c("Traditional", "Advanced"),result_types = c("player","team"), join_data = TRUE)


seq <- seq(22100001,22101320,8)


box_team<- box_scores(seq,box_score_types = c("Traditional", "Advanced"),result_types = "team", join_data = TRUE)  

box_player <-  box_scores(seq,box_score_types = c("Traditional", "Advanced"),result_types = "player", join_data = TRUE)




NBA_Standings <- read.csv("2012-18_standings.csv")
NBA_Standings <- select(NBA_Standings,-c(rankOrd,stk,wpyth13.91:lpyth16.5))

#if(NBA_Player_box_scores$gmDate == NBA_Standings$stDate & NBA_Player_box_scores$teamAbbr == NBA_Standings$teamAbbr){
  
  
```
We dont need officals names,divisions

```{r}
correlation <- cor(select_if(NBA_Player_box_scores,is.numeric))

corrplot(correlation,type = 'lower', diag = FALSE, method='color')

```

```{r}
ggplot(NBA_Player_box_scores, aes(playPTS,playMin,colour = teamRslt)) + geom_point() 

```
```{r}

ggplot(nba)

```{r}
min_recipe <- recipe(playMin ~ ., data = NBA_Player_box_scores ) %>% step_dummy(all_nominal_predictors()) %>% step_interact()